### ISSUE TITLE
Input System

### ISSUE THREAD

**Issue by thiagomvas** [thiagomvas/Basalt#1]
#### Tasks
- [x] Set up abstraction layer: IInputDevice, IKeyboard, IMouse, IGamepad
- [x] Set up basic input handling for keyboard and mouse.
- [x] Implement polling-based input processing.
- [x] Create simple input mappings class
