### ISSUE TITLE
Rework Raylib renderers

### ISSUE THREAD

**Issue by thiagomvas** [thiagomvas/Basalt#4]
Instead of using DrawSphere, DrawCube, etc, use models
#### Tasks
- [x] Use models to render instead
- [x] Change color properly
- [x] Make them affected by lights
